table Category_translation
	lineageTag: 3c593e9b-3ec9-4417-85eb-f652804f648d

	column product_category_name
		dataType: string
		lineageTag: de023498-02fb-48bb-ac04-7d75a94f9ada
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	column product_category_name_english
		dataType: string
		lineageTag: c2a73374-f5ce-49ac-8bed-8fb9409420bd
		summarizeBy: none
		sourceColumn: product_category_name_english

		annotation SummarizationSetBy = Automatic

	partition Category_translation = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost:3306", "ecommerce_analytics", [ReturnSingleDatabase=true]),
				    ecommerce_analytics_product_category_name_translation = Source{[Schema="ecommerce_analytics",Item="product_category_name_translation"]}[Data],
				    #"Trimmed Text" = Table.TransformColumns(ecommerce_analytics_product_category_name_translation,{{"product_category_name", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"product_category_name", Text.Clean, type text}}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Cleaned Text",{{"product_category_name_english", Text.Trim, type text}}),
				    #"Cleaned Text1" = Table.TransformColumns(#"Trimmed Text1",{{"product_category_name_english", Text.Clean, type text}})
				in
				    #"Cleaned Text1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

